/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.switch_api.api;

import io.swagger.switch_api.model.CreateTaskRequest;
import io.swagger.switch_api.model.Error;
import io.swagger.switch_api.model.TaskListResponse;
import io.swagger.switch_api.model.TaskResponse;
import java.util.UUID;
import io.swagger.switch_api.model.UpdateTaskRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-06-09T10:49:04.429+02:00")

@Api(value = "task", description = "the task API")
public interface TaskApi {

    @ApiOperation(value = "Create task", nickname = "createTask", notes = "Create new task", response = TaskResponse.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Task created successfully", response = TaskResponse.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 422, message = "Unprocessable entity. Codes: USER_ALREADY_EXISTS", response = Error.class) })
    @RequestMapping(value = "/task",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<String> createTask(@ApiParam(value = "Task object that has to be added" ,required=true )  @Valid @RequestBody CreateTaskRequest body,@ApiParam(value = "Podpis X-HMAC-SIGNATURE" ,required=true) @RequestHeader(value="X-HMAC-SIGNATURE", required=true) String X_HMAC_SIGNATURE);


    @ApiOperation(value = "Delete task", nickname = "deleteUser", notes = "Removes task", authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "No content"),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 404, message = "Task not found", response = Error.class),
        @ApiResponse(code = 422, message = "Unprocessable entity.", response = Error.class) })
    @RequestMapping(value = "/task/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTask(@ApiParam(value = "",required=true) @PathVariable("id") UUID id);


    @ApiOperation(value = "Get tasks list", nickname = "getAllTasks", notes = "Get all tasks data", response = TaskListResponse.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = TaskListResponse.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 422, message = "Unprocessable entity. Codes: USER_ALREADY_EXISTS", response = Error.class) })
    @RequestMapping(value = "/task",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<TaskListResponse> getAllTasks();


    @ApiOperation(value = "Get task", nickname = "getTaskById", notes = "Get specified task data", response = TaskResponse.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = TaskResponse.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 404, message = "Task not found", response = Error.class),
        @ApiResponse(code = 422, message = "Unprocessable entity. Codes: USER_ALREADY_EXISTS", response = Error.class) })
    @RequestMapping(value = "/task/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<TaskResponse> getTaskById(@ApiParam(value = "",required=true) @PathVariable("id") UUID id);


    @ApiOperation(value = "Update task", nickname = "updateUser", notes = "Update task data", response = TaskResponse.class, authorizations = {
        @Authorization(value = "basicAuth")
    }, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Success", response = TaskResponse.class),
        @ApiResponse(code = 400, message = "Bad request", response = Error.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Error.class),
        @ApiResponse(code = 404, message = "Task not found", response = Error.class),
        @ApiResponse(code = 422, message = "Unprocessable entity.", response = Error.class) })
    @RequestMapping(value = "/task/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<String> updateTask(@ApiParam(value = "",required=true) @PathVariable("id") UUID id,@ApiParam(value = "" ,required=true )  @Valid @RequestBody UpdateTaskRequest body,@ApiParam(value = "Podpis X-HMAC-SIGNATURE" ,required=true) @RequestHeader(value="X-HMAC-SIGNATURE", required=true) String X_HMAC_SIGNATURE);

}
